spring.application.name=ai-code-explainer

server.port=8080
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

cors.allowed-origin=http://localhost:5173
